const constant = {
  FETCH_ZIPCODE_REQUEST: "FETCH_ZIPCODE_REQUEST",
  FETCH_ZIPCODE_SUCCESS: "FETCH_ZIPCODE_SUCCESS",
  FETCH_ZIPCODE_FAILURE: "FETCH_ZIPCODE_FAILURE",
  UPDATE_SEARCH_HISTORY: "UPDATE_SEARCH_HISTORY"
};

export default constant;
