const constant = {
  FETCH_ZIPCODE_REQUEST: "FETCH_ZIPCODE_REQUEST",
  FETCH_ZIPCODE_SUCCESS: "FETCH_ZIPCODE_SUCCESS",
  FETCH_ZIPCODE_FAILURE: "FETCH_ZIPCODE_FAILURE",
  UPDATE_SEARCH_HISTORY: "UPDATE_SEARCH_HISTORY",
  FETCH_STOCK_DATA_FROM_QUANTL_REQUEST: "FETCH_STOCK_DATA_FROM_QUANTL_REQUEST",
  FETCH_STOCK_DATA_FROM_QUANTL_FAILURE: "FETCH_STOCK_DATA_FROM_QUANTL_FAILURE",
  FETCH_STOCK_DATA_FROM_QUANTL_SUCCESS: "FETCH_STOCK_DATA_FROM_QUANTL_SUCCESS"
};

export default constant;
